---
# tasks file for ansible-apache-httpd

- name: Assert supported platform
  tags: httpd
  assert:
    that: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: Include required vars
  tags: httpd
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install httpd_server
  tags: httpd
  with_items: httpd_packages
  become: true
  action: "{{ ansible_pkg_mgr }} state=installed name={{ item }}"

- name: Install modules
  tags: httpd
  with_items: httpd_modules
  become: true
  action: "{{ ansible_pkg_mgr }} state=installed name={{ httpd_modules_pacakge_prefix }}_{{ item }}"

- name: Remove default vhosts
  tags: httpd
  with_items: httpd_default_vhosts
  notify: reload httpd
  become: true
  file:
    state=absent
    path="{{ httpd_conf_basepath }}/conf.d/{{ item }}"

- name: Add vhosts
  tags: httpd
  with_items: httpd_vhosts
  notify: reload httpd
  become: true
  template:
    dest="{{ httpd_conf_basepath }}/conf.d/{{ item.name }}.conf"
    src="{{ item.template|default(httpd_default_template) }}"
    owner=0
    group=0
    mode="{{ item.mode|default(httpd_default_vhost_mode) }}"

- name: Set SEBooleans
  tags: httpd
  with_items: httpd_sebooleans
  when: ansible_os_family  == 'RedHat'
  become: true
  seboolean:
    name: "{{ item.name }}"
    state: "{{ item.state|default('true') }}"
    persistent: true

- name: Ensure service is up and enabled
  tags: httpd
  become: true
  service: name="{{ httpd_servicename}}" state=started enabled=yes
