---
# handlers file for ansible-apache-httpd
- name: reload httpd
  tags: httpd
  become: true
  service: name="{{ httpd_servicename }}" state=reloaded

- name: restart httpd
  tags: httpd
  become: true
  service: name="{{ httpd_servicename }}" state=restarted
